Добавить новую систему логирования для активити
CasperKHV/Weather pull request #19
Opened 2024-03-19 18:01 UTC by CasperKHV

2024-03-20 05:29 UTC, umpteenthdev commented on app/src/main/java/com/casperkhv/weather/ActivityLifecycleLog.kt
> +class ActivityLifecycleLog : ActivityLifecycleCallbacks {
Это ведь не лог, а всё-так коллбэк. Предлагаю переименовать в `ActivityLifecycleLoggingCallback`.

2024-03-20 05:30 UTC, umpteenthdev commented on app/src/main/java/com/casperkhv/weather/ActivityLifecycleLog.kt
> +class ActivityLifecycleLog : ActivityLifecycleCallbacks {
Предлагаю сделать класс `internal`. В целом следует делать область видимости класса минимально допустимой, даже если пока этот код лежит в модуле, который другими не используется и кажется, что не будет.

2024-03-20 05:32 UTC, umpteenthdev commented on app/src/main/java/com/casperkhv/weather/ActivityLifecycleLog.kt
> +    private val TAG: String = "ActivityLifecycleLog"
Предлагаю сделать похитрее. Чтобы потом жизненный цикл фрагментов и активити можно было по одному фильтру смотреть. Например, можно сделать здесь `lifecycle/activity`, а для фрагментов потом сделать `lifecycle/fragment`. Тогда чтобы смотреть всё вместе можно будет установить в LogCat фильтр `lifecycle/`

2024-03-20 05:35 UTC, umpteenthdev commented on app/src/main/java/com/casperkhv/weather/ActivityLifecycleLog.kt
> +    private val TAG: String = "ActivityLifecycleLog"
Если объявляется `val` внутри класса, то она никогда не описывается капсом, потому что это не константа и не static переменная как в Java. По смыслу строковый литерал надо выносить в константу, это да. Предлагаю сделать в классе `companion object` и перенести этот `val` в него, добавив модификатор `const`. Тогда это будет `static` переменная, что позволит компилятору избежать обращений программы к переменной, так как он в места вызовов этой константы просто литералы скопирует.

2024-03-20 05:38 UTC, umpteenthdev commented on app/src/main/java/com/casperkhv/weather/ActivityLifecycleLog.kt
> +    override fun onActivityCreated(p0: Activity, p1: Bundle?) {
Имена переменных обфусцированные. Обычно это говорит о том, что у тебя IDE не проиндексировала библиотеку, из которой ты используешь класс. Нажми `ctrl` + `B` на `ActivityLifecycleCallbacks` и если там ещё будет непонятный код внутри, то наверху должна быть синяя полоса с кнопкой `index`. После индексации библиотеки заново переопредели методы в этом классе, чтобы имена переменных стали читаемыми

2024-03-20 05:44 UTC, umpteenthdev commented on app/src/main/java/com/casperkhv/weather/ActivityLifecycleLog.kt
> +        Log.d(TAG, "${p0.localClassName} now created")
В каждом логе ты используешь `now`. С одной стороны это попытка сделать лог более читаемым человеку, но по сути это только мешает. Тот, что увидит тег лога уже будет понимать о чём речь. В случае с `onActivitySaveInstanceState` лог вообще звучит странно. Нельзя сказать now и при этом описать не состояние, а какое-то действие. Если `now stopped` - это `сейчас остановленный`, то есть по сути тут пассивный залог, то про `now saved instance state` непонятно как перевести, потому что под пассив это не попадает, а если не пассив, то это now + прошедшее время, что тоже невозможно. 
Короче предлагаю упростить. Просто писать везде `"имя_класса : действие"`. Действие при этом брать как имя метода без `onActivity`, так как то, что это в активити происходит будет по логу понятно.

2024-03-20 05:45 UTC, umpteenthdev commented on app/src/main/java/com/casperkhv/weather/WeatherApplication.kt
> +
Пустая строка лишняя. Здесь бы нам detekt подсказал, который мы пока не смержили :)

2024-03-20 05:46 UTC, umpteenthdev commented on app/src/main/java/com/casperkhv/weather/WeatherApplication.kt
> +        val activityLifecycleLog: ActivityLifecycleLog = ActivityLifecycleLog()
Тип переменной можно не указывать, здесь в этом смысла ведь нет. Автовыведение типа сработает и читаться при этом будет легче

2024-03-20 05:47 UTC, umpteenthdev requested changes
Нужно поправить замечания

2024-03-20 12:01 UTC, CasperKHV commented on app/src/main/java/com/casperkhv/weather/ActivityLifecycleLog.kt
> +    private val TAG: String = "ActivityLifecycleLog"
Отличная идея!

2024-03-20 15:21 UTC, umpteenthdev commented on app/src/main/java/com/casperkhv/weather/ActivityLifecycleLoggingCallback.kt
> +        private const val TAG: String = "lifecycle/activity"
Константам тип обычно не указывают, там и так только примитивы и строка. Без этого понятно :) И давай `companion object` в конец класса перенесем. Соглашения бывают разные и это вкусовщина, но мне кажется так удобнее, так как он там в глаза не бросается и не мешает как в начале. В начале обычно ведь может быть набор свойств, ещё и `init` блок, вместо с компаньоном это в мешанину превращается всё

2024-03-21 12:25 UTC, CasperKHV commented on app/src/main/java/com/casperkhv/weather/ActivityLifecycleLoggingCallback.kt
> +        private const val TAG: String = "lifecycle/activity"
Согласен, блок init более уместен в начале... Хотя константы по смыслу в моём представлении близки к свойствам, которые мы используем далее в классе, всё же эта блочная структура делает их громоздкими и логично их перенести, да.

2024-03-21 12:49 UTC, umpteenthdev approved these changes

2024-03-21 13:05 UTC, merged